name: Bazel Build
run-name: ${{ github.actor }} is building with bazel
on: [push]
jobs:
  hello-world:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_platform:
          - armv7-linux-musleabihf
          - aarch64-linux-musl
          - x86_64-linux-musl
    steps:
      - run: echo "Hello from github actions"
      - run: echo "The job is triggered by ${{ github.event_name }}"
      - run: echo "OS is ${{ runner.os }}"
      - run: echo branch name is ${{ github.ref }}
      - name: Checkout
        uses: actions/checkout@v4.1.0
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: "bazel-${{ matrix.target_platform }}"
      - name: Build all
        run: >
          bazel build //...
          --platforms=//:${{ matrix.target_platform }}
          --incompatible_enable_cc_toolchain_resolution
          --toolchain_resolution_debug=@rules_rust//rust:toolchain
